title: Complete Intro to React
email: btholt+citr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A two day workshop to learn React and the surrounding ecosystem
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://btholt.github.io/complete-intro-to-react" # the base hostname & protocol for your site
twitter_username: holtbt
github_username:  btholt

# Build settings
markdown: kramdown
